name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Initialize Terraform
        run: terraform init -backend-config=environments/${{ matrix.environment }}/backend.tfvars

      - name: Plan Terraform
        run: terraform plan -var-file=environments/${{ matrix.environment }}/terraform.tfvars

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: terraform apply -auto-approve -var-file=environments/${{ matrix.environment }}/terraform.tfvars
