name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'

  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Configure AWS credentials 
        env:
          AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials configured"
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        

      - name: Initialize Terraform
        run: terraform init -backend-config=environments/${{ matrix.environment }}/backend.tf

      - name: Plan Terraform
        run: terraform plan -var-file=environments/${{ matrix.environment }}/terraform.tfvars

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: terraform apply -auto-approve -var-file=environments/${{ matrix.environment }}/terraform.tfvars
